Add illustrations (TODO)
Anmol-Baranwal/Awesome-Illustrations-4Projects pull request #22
Opened 2022-10-06 23:09 UTC by jpacsai

**List of illustrations included in this PR:**

Solves issue: #17 

 [Scratches](https://craftwork.design/downloads/scratches/)
 [Tiny Dribbble Shots Constructor](https://craftwork.design/downloads/tiny-dribbble-shots-constructor/)
 [Desk Dudes](https://growwwkit.com/illustrations/desk-dudes/)
 [The Townies](https://growwwkit.com/illustrations/the-townies/)
 [Lil Helpers](https://growwwkit.com/illustrations/lil-helpers/)
 [The Carltons](https://growwwkit.com/illustrations/the-carltons/)
 [Neighbour Larry](https://growwwkit.com/illustrations/neighbour-larry/)
 [Jane](https://growwwkit.com/illustrations/jane/)
 [Springtale](https://growwwkit.com/illustrations/springtale/)
 [Office Dave](https://growwwkit.com/illustrations/office-dave/)
 [Workaholics](https://growwwkit.com/illustrations/workaholics/)
 [Isotopia](https://growwwkit.com/illustrations/isotopia/)
 [Polydrome](https://growwwkit.com/illustrations/polydrome/)
 [Aventine](https://growwwkit.com/illustrations/aventine/)
 [Fundango](https://growwwkit.com/illustrations/fundango/)

---

- [x] I have read the [Contribution Guidelines]

2022-10-07 17:45 UTC, Anmol-Baranwal requested changes
Please make these changes in a single commit.

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +    - [Neighbour Larry](https://growwwkit.com/illustrations/neighbour-larry/)
```suggestion
    No Need for this Illustration as I already checked it in the issue since it is a duplicate of Larry Character which is already included.
    Kindly remove this.
```

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +    - [Scratches](https://craftwork.design/downloads/scratches/)
Just correct the order as `Scratches` will come before `Seoul`

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://growwwkit.com/illustrations/neighbour-larry/"><img width='700' src='https://user-images.githubusercontent.com/34191321/194434334-bf827343-844f-42d8-8e29-c748639f8532.png' alt="Neig
Remove this, due to the above reason.

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://craftwork.design/downloads/scratches/"><img width='700' src='https://user-images.githubusercontent.com/92253071/193480665-4f035a53-902a-4ecd-9b37-a174e00c8183.png' alt="Seoul_freem
I think you have mistakenly changed the image URL, kindly make it as before.
URL: `https://www.kapustin.co/seoul`

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://craftwork.design/downloads/scratches/"><img width='700' src='https://user-images.githubusercontent.com/34191321/194415465-4190168e-66a2-4809-8d2a-875ff2687c54.png' alt="Scratches_f
This illustration would be in the free category. 
Although it seems at first instance due to `Download with pro access` but one can download all the assets for free. Change the corresponding menu and alt text.
Do let me know if I am wrong.

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://craftwork.design/downloads/tiny-dribbble-shots-constructor/"><img width='700' src='https://user-images.githubusercontent.com/34191321/194421585-c93825ae-8d3f-4caf-88ec-0db5e359380d
- Change Title URL to `https://craftwork.design/downloads/tiny-dribbble-shots-constructor`
- This illustration would be in the free category. Make necessary changes.
- Change alt text to `Tiny_Dribbble_Shots_Constructor_free_illustrations`

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +    - [Office Dave](https://growwwkit.com/illustrations/office-dave/)
correct the order

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://growwwkit.com/illustrations/desk-dudes/"><img width='700' src='https://user-images.githubusercontent.com/34191321/194423177-11260cc2-8920-4e1d-a034-92e203146670.png' alt="Desk Dude
change alt text to `Desk_Dudes_paid_illustrations`

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://growwwkit.com/illustrations/lil-helpers/"><img width='700' src='https://user-images.githubusercontent.com/34191321/194424332-543c02fb-46c5-49f6-bc4e-5ba82c894662.png' alt="Lil Help
change alt text to `Lil_Helpers_paid_illustrations`

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://growwwkit.com/illustrations/office-dave/"><img width='700' src='https://user-images.githubusercontent.com/34191321/194427793-0406d730-3ff3-4811-b53d-7e2261e9ba72.png' alt="Office D
- Change the order as mentioned above
- Change alt text to `Office_Dave_paid_illustrations`

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://growwwkit.com/illustrations/the-carltons/"><img width='700' src='https://user-images.githubusercontent.com/34191321/194425337-28e80ee2-8a75-48e9-9ccd-5613b569280b.png' alt="The Car
- Change alt text to `The_Carltons_paid_illustrations`

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://growwwkit.com/illustrations/the-townies/"><img width='700' src='https://user-images.githubusercontent.com/34191321/194423843-67ad5302-b459-4b38-b630-bafb14830c93.png' alt="The Town
- Change alt text to `The_Townies_paid_illustrations`

2022-10-07 17:45 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://growwwkit.com/illustrations/workaholics/"><img width='700' src='https://user-images.githubusercontent.com/34191321/194429370-f48f5a53-0f6b-45c0-b54d-baabb5c974a9.png' alt="Workahol
- change Image URL to `https://user-images.githubusercontent.com/74038190/194617817-1f9afa91-635b-4ee1-b4c6-dd87ff5647c3.png`.

2022-10-08 13:22 UTC, jpacsai commented
@Anmol-Baranwal  I have missed some issues in the first fix commit, made onther commit, sorry about it. all done now

2022-10-08 13:31 UTC, Anmol-Baranwal approved these changes

2022-10-08 13:33 UTC, merged

2022-10-08 13:33 UTC, Anmol-Baranwal commented
Appreciate your contribution :)