feat: add illustrations
Anmol-Baranwal/Awesome-Illustrations-4Projects pull request #25
Opened 2022-10-10 23:13 UTC by jpacsai

List of Illustrations included in this PR:

Solves Issue https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects/issues/18

[EMOJIZ](https://emojiz.design/)
[ANIMALZ](https://animalz.design/)
[AVATARZ](https://www.avatarz.design/)
[Nutrition Icons](https://drawkit.com/product/nutrition-icons)
[Mental Health Icons](https://drawkit.com/product/mental-health-icons)
[Website States Icons](https://drawkit.com/product/website-states-icons)
[Education Icons](https://drawkit.com/product/free-education-icons)
[Ecology & Nature Icons](https://drawkit.com/product/ecology-nature-free-icons)
[Startups and SaaS Icons](https://drawkit.com/product/startups-and-saas-icons)
[COVID-19 Icons](https://drawkit.com/product/covid-19)
[Food & Drink Icons](https://drawkit.com/product/food-drink)
[Ugly Delicious](https://drawer.design/products/ugly-delicious/)
[Social Work & Charity](https://drawkit.com/product/social-work-charity-illustrations)
[COVID-19 & Vaccinations](https://drawkit.com/product/covid-19-vaccinations)
[Product & Project Managers](https://drawkit.com/product/project-product-manager-illustrations)

---

- [x] I have read the [Contribution Guidelines]

2022-10-12 21:24 UTC, jpacsai commented
@Anmol-Baranwal I have resolved the merge conflict

2022-10-13 09:52 UTC, Anmol-Baranwal commented
@jpacsai  
Why is there a gap in the images you have uploaded on the left & right sides?
e.g.
![Screenshot (3987)](https://user-images.githubusercontent.com/34191321/194713789-cd2508a7-a719-4bb6-90c6-18e6920c6bab.png)

I am just asking to get to know the reason behind this. Is it your specific configuration or default style?

2022-10-13 10:20 UTC, jpacsai commented
It's my default style, I have a big screen probably that's the reason

2022-10-13 10:21 UTC, Anmol-Baranwal commented
> @Anmol-Baranwal It's my default style, I have a big screen probably that's the reason

Okay, no worries.

2022-10-13 10:43 UTC, Anmol-Baranwal requested changes
Please make these minor changes in a single commit.

And please do not resolve the conflicts since it seems that some illustrations are added again.

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://drawkit.com/product/covid-19"><img width='700' src='https://user-images.githubusercontent.com/34191321/194713789-cd2508a7-a719-4bb6-90c6-18e6920c6bab.png' alt="COVID-19_icons_free_
- change the src link to `https://user-images.githubusercontent.com/74038190/195566597-f1ce10d9-83bb-4a9f-b514-2ed1195174c0.png` in covid-19 icons

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://drawkit.com/product/covid-19-vaccinations"><img width='700' src='https://user-images.githubusercontent.com/34191321/194714608-5619de4e-2d0d-4023-ad47-95eb5be1d299.png' alt="COVID-1
- change the src link to `https://user-images.githubusercontent.com/74038190/195567351-f9f769ff-c308-4088-b71a-1617a14b030d.png` in covid-19-vaccinations

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://drawkit.com/product/ecology-nature-free-icons"><img width='700' src='https://user-images.githubusercontent.com/34191321/194713342-0a5264a2-1ebe-4497-9dee-f7136f29033e.png' alt="eco
- change the src link to `https://user-images.githubusercontent.com/74038190/195568112-2d82cf0b-43f8-4e1a-9d0d-bb9628591100.png` in ecology-nature-free-icons

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://www.drawkit.com/product/free-education-icons"><img width='700' src='https://user-images.githubusercontent.com/34191321/194964105-d0659d45-1c5f-4a31-8f29-2c82333232fe.png' alt="educ
- change the src link to `https://user-images.githubusercontent.com/74038190/195569147-2bcdf4bc-5fd4-4823-a306-6ef08039cc6d.png` in Education Icons

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://www.drawkit.com/product/food-drink"><img width='700' src='https://user-images.githubusercontent.com/34191321/194964905-fdc1c359-3337-464f-8632-8bf4965af8e5.png' alt="food_&_drink_i
- change the src link to `https://user-images.githubusercontent.com/74038190/195569620-ae39b498-c7f6-4b87-942b-7e6c7a343a50.png`

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://www.drawkit.com/product/mental-health-icons"><img width='700' src='https://user-images.githubusercontent.com/34191321/194963389-3399dedb-e379-462e-890b-bbe449b8d9da.png' alt="Menta
- change the src link to `https://user-images.githubusercontent.com/74038190/195569982-89003c4d-1116-4aeb-bcb9-8d0b33dbd186.png`

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://www.drawkit.com/product/nutrition-icons"><img width='700' src='https://user-images.githubusercontent.com/34191321/194963072-2a0c777d-e24e-48d7-8156-b185888eb03a.png' alt="nutrition
- change the src link to `https://user-images.githubusercontent.com/74038190/195570876-ffac6d16-8f67-4899-bed2-84cefe6b1378.png`

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://drawkit.com/product/product-project-managers-illustrations"><img width='700' src='https://user-images.githubusercontent.com/74038190/194872674-c12a20e6-d262-4a0f-b376-e8eb5643435d.
- add a format `AI`

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://www.drawkit.com/product/startups-and-saas-icons"><img width='700' src='https://user-images.githubusercontent.com/34191321/194964526-e758799c-320c-422e-8a16-f27b65b2ce19.png' alt="s
- change the src link to `https://user-images.githubusercontent.com/74038190/195572891-c6cf167b-bba3-4e17-ab70-326877219f53.png`

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://drawer.design/products/ugly-delicious/"><img width='700' src='https://user-images.githubusercontent.com/74038190/194874593-f301ed8b-8c58-4507-aabb-54a826d54f56.png' alt="ugly_delic
- change the src link to `https://user-images.githubusercontent.com/74038190/195573490-a4751388-a786-4b57-b53d-df12c412064b.png` (the size is changed)

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://www.drawkit.com/product/website-states-icons"><img width='700' src='https://user-images.githubusercontent.com/34191321/194963725-03530fdd-112a-4e11-bcad-10bcc45ccdfd.png' alt="webs
- change the src link to `https://user-images.githubusercontent.com/74038190/195574040-c35d2018-cdbd-4d53-b1e8-27c0c730d8e2.png`

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://animalz.design/"><img width='700' src='https://user-images.githubusercontent.com/34191321/194711955-ef309dbf-5620-4737-ab62-ff0aabcdd9f0.png' alt="Animalz_freemium_illustrations" /
- change the src link to `https://user-images.githubusercontent.com/74038190/195574700-bffeaa34-052f-4886-9daa-2d4daf7d43ac.png`

2022-10-13 10:43 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://emojiz.design/"><img width='700' src='https://user-images.githubusercontent.com/34191321/194711655-63359e54-bfee-493d-83e1-3b8b14bb4915.png' alt="Emojiz_freemium_illustrations" /><
- change the src link to `https://user-images.githubusercontent.com/74038190/195575740-741a625a-7631-4e4e-9d24-5db0f1f30932.png`

2022-10-13 20:25 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://drawer.design/products/ugly-delicious/"><img width='700' src='https://user-images.githubusercontent.com/74038190/194874593-f301ed8b-8c58-4507-aabb-54a826d54f56.png' alt="ugly_delic
This was not needed, since your previous one exactly matches my recommended one.

2022-10-13 20:27 UTC, Anmol-Baranwal approved these changes

2022-10-13 20:28 UTC, merged

2022-10-13 20:28 UTC, Anmol-Baranwal commented
Appreciate your contribution :)