Added Yaay in Paid Category
Anmol-Baranwal/Awesome-Illustrations-4Projects pull request #41
Opened 2023-02-25 11:47 UTC by PiseAtharva

resolves #32 

## Name of Illustration
[Yaay](https://www.ls.graphics/products/yaay)

 

 

## Illustration Image

<img width='700' src='https://user-images.githubusercontent.com/88548999/221354920-47a59d6c-f38b-41a0-ac85-dfbb26f75e0a.png' alt="Workaholics_paid_illustrations" />

---

## Checklist

- [x] Name the PR fix: add `Yaay`.
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] You've linked the PR to the correct issue.
- [x] I have read the [Contribution Guidelines](https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects/blob/main/CONTRIBUTING.md)

2023-02-25 11:48 UTC, Anmol-Baranwal commented
Thanks for your contribution, we will soon check your PR @PiseAtharva :)

2023-02-25 13:23 UTC, Anmol-Baranwal requested changes
@PiseAtharva 

- Add this illustration in the Menu as well.

Do these changes in a single commit in this PR.

2023-02-25 13:23 UTC, Anmol-Baranwal commented on README.md
> +| <a href="https://www.ls.graphics/products/yaay"><img width='700' src='https://user-images.githubusercontent.com/88548999/221354920-47a59d6c-f38b-41a0-ac85-dfbb26f75e0a.png' alt="Workaholics_paid_il
```suggestion
| <a href="https://www.ls.graphics/products/yaay"><img width='700' src='https://user-images.githubusercontent.com/88548999/221354920-47a59d6c-f38b-41a0-ac85-dfbb26f75e0a.png' alt="Yaay_paid_illustrations" /></a> | [Yaay](https://www.ls.graphics/products/yaay)  <br><br> 💰 Paid <br><br>Format <br> • Sketch<br>• Adobe Illustrator<br>• Adobe Xd<br>• Figma<br>• SVG<br>• Affinity<br><br> ✌️Author <br> LS Graphics  |
```

2023-02-26 12:52 UTC, PiseAtharva commented on README.md
> +| <a href="https://www.ls.graphics/products/yaay"><img width='700' src='https://user-images.githubusercontent.com/88548999/221354920-47a59d6c-f38b-41a0-ac85-dfbb26f75e0a.png' alt="Workaholics_paid_il
thanks for the suggestion

2023-02-26 19:15 UTC, Anmol-Baranwal approved these changes
Well done !!

2023-02-26 19:17 UTC, merged

2023-02-26 19:18 UTC, Anmol-Baranwal commented
Appreciate your contribution :)